name: Redpill Build All

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      platform:
        description: 'all DS3615xs DS3617xs DS918+ DS920+ DS3622xs+'
        required: true
        default: 'all' 
        type: choice
        options:
        - all
        - DS3615xs
        - DS3617xs
        - DS918+
        - DS920+
        - DS3622xs+

      version:
        description: '7.1.0-42661 7.0.1-42218'
        required: true
        default: '7.0.1-42218' 
        type: choice
        options:
        - 7.1.0-42661
        - 7.0.1-42218-JUN
        - 7.0.1-42218

env:
  releasetag: $(date +"%Y.%m.%d-%H%M")

jobs:
  DS3615xs:
    if: ${{ github.event.inputs.platform == 'DS3615xs' }}  || ${{ github.event.inputs.platform == 'all' }}
    uses: wjz304/Redpill_Build/.github/workflows/Build.yml@main
    with:
      releasetag: ${{ env.releasetag }}
      platform: 'DS3615xs'
      version: ${{ github.event.inputs.version }}
    secrets:
      token: ${{ secrets.TOKEN }}

  DS3617xs:
    if: ${{ github.event.inputs.platform == 'DS3617xs' }}  || ${{ github.event.inputs.platform == 'all' }}
    uses: wjz304/Redpill_Build/.github/workflows/Build.yml@main
    with:
      releasetag: ${{ env.releasetag }}
      platform: 'DS3617xs'
      version: ${{ github.event.inputs.version }}
    secrets:
      token: ${{ secrets.TOKEN }}

  DS918p:
    if: ${{ github.event.inputs.platform == 'DS918+' }}  || ${{ github.event.inputs.platform == 'all' }}
    uses: wjz304/Redpill_Build/.github/workflows/Build.yml@main
    with:
      releasetag: ${{ env.releasetag }}
      platform: 'DS918+'
      version: ${{ github.event.inputs.version }}
    secrets:
      token: ${{ secrets.TOKEN }}

  DS920p:
    if: ${{ github.event.inputs.platform  == 'DS920+' }}  || ${{ github.event.inputs.platform == 'all' }}
    uses: wjz304/Redpill_Build/.github/workflows/Build.yml@main
    with:
      releasetag: ${{ env.releasetag }}
      platform: 'DS920+'
      version: ${{ github.event.inputs.version }}
    secrets:
      token: ${{ secrets.TOKEN }}

  DS3622xsp:
    if: ${{ github.event.inputs.platform == 'DS3622xs+' }}  || ${{ github.event.inputs.platform == 'all' }}
    uses: wjz304/Redpill_Build/.github/workflows/Build.yml@main
    with:
      releasetag: ${{ env.releasetag }}
      platform: 'DS3622xs+'
      version: ${{ github.event.inputs.version }}
    secrets:
      token: ${{ secrets.TOKEN }}
